### ISSUE TITLE
Wrong Course Highlighted when seeing its contents

### ISSUE THREAD

**Issue by Dayal-Kumar** [Aniruddha-Deb/MoodleSidebarPlugin#2]
First of all, thanks for the great extension👍.

Please see :
The selected course is PYL102 but, NLN101 is being highlighted in the sidebar. And, if I select any course lower in the list, its sub-list won't be shown.
And it would be great if only the courses of this semester appear in the sidebar.
![image](https://user-images.githubusercontent.com/83410988/127904292-de35cf7b-b00c-4d87-b08e-e3ac77b9254a.png)

**Comment by Aniruddha-Deb** [comment]
Hi,

This is a known issue, thanks for pointing it out. If you click on, say COL106 for example, the course tree opens up under courses -> managed courses -> semester 2101 -> 2101 - COL106. Because of this inconsistency, I couldn't come up with a simple solution for this, as moodle displays the course tree depending on the position of the course, which is vague.

<img width="311" alt="Screenshot 2021-08-02 at 11 51 33 PM" src="https://user-images.githubusercontent.com/14949866/127906541-0513097a-4c21-47eb-9b9d-d6073f86e6e6.png">

A longer solution would involve constructing my own tree of moodle courses, and managing the left sidebar entirely using the plugin rather than just the simple find/replace that the plugin does now, but since implementing this is not worth the effort, so far I've lived with this bug :P if you have a better solution though, please let me know :)
